--Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Exploring All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers' ;


--Exploring All Countries Our Customers Come From
SELECT DISTINCT
Country
FROM gold.dim_customers;

--Exploring All Categories 'The Major Divisions'
SELECT DISTINCT
category,
subcategory,
product_name
FROM gold.dim_products
Order By 1,2,3;

--Find the date of first , last order and years of sales available
SELECT
Min(order_date) as First_order,
Max(order_date) as Last_order,
Datediff(YEAR,Min(order_date) ,Max(order_date)) as Total_years
FROM gold.fact_sales;

--Find the youngest and oldest customers
SELECT
Datediff(Year,Min(birthdate),Getdate()) as Oldest_customer,
Datediff(Year,Max(birthdate),Getdate()) as Youngest_customer
FROM gold.dim_customers;


--Generating a report that has all the key metrics of the business
SELECT 'Total_Sales' as Measure_Name,
Sum(sales_amount) as Measure_Value
FROM gold.fact_sales
UNION ALL
SELECT 'Total_Quantity' as Measure_Name,
Sum(quantity) as Measure_Value
FROM gold.fact_sales
UNION ALL
SELECT 'Avg_Price' as Measure_Name,
Avg(Price) as Measure_Value
FROM gold.fact_sales
UNION ALL
SELECT 'Total_Order' as Measure_Name,
Count(DISTINCT order_number) as Measure_Value
FROM gold.fact_sales
UNION ALL
SELECT 'Total_product' as Measure_Name,
COUNT(product_key) as Measure_Value
FROM gold.dim_products
UNION ALL
SELECT 'Total_customers' as Measure_Name,
Count(customer_key) as Measure_Value
FROM gold.dim_customers
UNION ALL
SELECT 'Total_customers_Ordered' as Measure_Name,
Count(DISTINCT customer_key) as Measure_Value
FROM gold.fact_sales;

--Find total customer by countries
SELECT
country,
Count(customer_key) as Total_customers
FROM gold.dim_customers
Group By country
order by Total_customers desc;

--Find total customer by gender
SELECT
gender,
Count(customer_key) as Total_customers
FROM gold.dim_customers
Group By gender
order by Total_customers desc;

--Find total product by category
SELECT
Category,
Count(product_id) as Total_Product
FROM gold.dim_products
Group By Category
order by Total_Product desc;

--What is the average cost in each category?
SELECT
Category,
Avg(cost) as Avg_cost
FROM gold.dim_products
Group By Category
order by Avg_cost desc;

--What is the total revenue generated by each category?
SELECT
p.category,
Sum(f.sales_amount) as Total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products as p
on f.product_key=p.product_key
Group By p.category
order by Total_revenue desc;

--Find total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
Sum(s.sales_amount) as Total_revenue
FROM gold.dim_customers as c
LEFT JOIN gold.fact_sales as s
on c.customer_key=s.customer_key
Group By c.customer_key,c.first_name,c.last_name
order by Total_revenue desc;

--What is the distribution of sold item across countries?
SELECT
c.country,
Sum(s.quantity) as Total_item_sold
FROM gold.dim_customers as c
LEFT JOIN gold.fact_sales as s
on c.customer_key=s.customer_key
Group By c.country
order by Total_item_sold desc;

--Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
Sum(s.sales_amount) as total_Sales
FROM gold.dim_products as p
INNER JOIN gold.fact_sales as s
on p.product_key=s.product_key
Group By p.product_name
Order By total_Sales desc;

--What is the 5 worst performing products in terms of sales?
SELECT *
FROM (
SELECT
p.product_name,
Sum(s.sales_amount) as total_Sales,
Row_number() over(order by Sum(s.sales_amount)) as Rank_worst_products
FROM gold.dim_products as p
INNER JOIN gold.fact_sales as s
on p.product_key=s.product_key
Group By p.product_name )t
Where Rank_worst_products<6;